### ISSUE TITLE
Copycat of NewPipe

### ISSUE THREAD

**Issue by SecUpwN** [martykan/webTube#1]
Good evening @martykan, I have just discovered that you did a pure copy of [NewPipe](https://github.com/theScrabi/NewPipe) by @theScrabi and also provide it on F-Droid now. You even copied the project description on F-Droid. I know that the app of @theScrabi is licensed GPLv3+, but how come you don't give *any* credit to its original author? And what are you planning to do with this copy instead of contributing a few bits of code to the original app?

**Comment by martykan** [comment]
Nope. It's completely different. I didn't write the description on F-Droid, but I am aware that the description is copied form NewPipe, but that's not my fault. This app is actually only a WebView wrapper around the website. I suggest you to actually install an app, before making these assumptions.

**Comment by theScrabi** [comment]
@SecUpwN he is right, it's not a copy, its just an app providing the youtube website.
@martykan I find your app kind of nice. Maybe you could add some Newpipe support, so your video could be opened in your app, but than watched over in NP. :)

**Comment by martykan** [comment]
There actually is a bit of integration - when you click the Open in browser button, you can choose NewPipe too. I actually use this a lot, especially for background playback. I looked into the option of automatically playing videos in NewPipe, but that I am not sure how well would that work.
