### ISSUE TITLE
[FR] NewPipe FRs

### ISSUE THREAD

**Issue by ildar** [martykan/webTube#10]
I see t he two apps are competing to death :)
Did you consider the feature requests of the NewPipe https://github.com/theScrabi/NewPipe/issues/ ?
I am specifically interested in https://github.com/theScrabi/NewPipe/issues/6

**Comment by martykan** [comment]
Well, Newpipe is a full native app and WebTube just wraps around the YouTube website to make it look native. So I can't change that much of the website itself.

The search history is already there, just enable it in settings. You have to type the first letter of the query for the history to show up.

**Comment by ildar** [comment]
The search history works only when logged in. I'd like to have a non-cloud
aka local history.
Thanks.

**Comment by martykan** [comment]
Thats not going to be easy, but I'll try.

**Comment by Natureshadow** [comment]
Hmm...

I'd say: If you want online YouTube, use WebTube; if you want "non-cloud", use NewPipe.

**Comment by theScrabi** [comment]
@my_competitor ;) You could implement your own search bar, and than if someone searches with that bar, you could store the searched strings inside a database.
Also if you have working code, consider to also contributing it to NP :P

**Comment by ildar** [comment]
I see the search history is stored which is very nice!!!
Unfortunately it doesn't work quite as expected. The stored items should
appear as soon as the search bar appears. Can you fix it please?

**Comment by martykan** [comment]
I will try.

**Comment by ildar** [comment]
Emm, sorry, failed to reach the last request?

**Comment by martykan** [comment]
I have it my To-Do list, but this issue is about NewPipe feature requests, which are not really relevant, because of the heavy differences betwee theese apps.

**Comment by ildar** [comment]
Alright, not urgent now when searches may be "favorit"ed. Thanks!
