### ISSUE TITLE
What is the Dns and the cookie policy?

### ISSUE THREAD

**Issue by gerroon** [martykan/webTube#16]
Hi

Can you please explain if this is using the proxy dns or not when it is in proxy mode?

How long does it keep the cookies? I presume it sets cookies since it is a web app.

thanks

**Comment by martykan** [comment]
Android uses the DNS provided by DHCP. It is provided by your router or you can change it by setting a static IP, while connecting to a WiFi network. I don't think you can change the DNS on a per app basis.

Cookies are kept pretty much forever, so you don't get logged out of your account.

**Comment by gerroon** [comment]
Hi

Firefox has an option to use socs proxy's dns server if it is in proxy mode. Would not make sense if this app does the same thing too? Otherwise people who use proxy in this app will just leak dns.

"network.proxy.socks_remote_dns"


As far as the cookies goes, I personally do not have a youtube account and as a user I prefer to have only session cookies. Would that be possible have an option to get rid of cookies after the app closes?

**Comment by martykan** [comment]
Tor is a bit more complicated than just a proxy. In Tor, the DNS request is made by the exit node, not directly from the device, so it's safe. Also, when using Tor, all cookies are entirely disabled.

**Comment by gerroon** [comment]
@martykan 

Thanks for the update.

I use tor mode to bypass my restrictive firewall not to evade any surprassion however it is always good to practice good security.


thanks
