### ISSUE TITLE
menu larger than screen

### ISSUE THREAD

**Issue by txt-file** [martykan/webTube#19]
On my 800x480 px display the menu is bigger than ne displayable area. If I have my phone in landscape I only see the "refresh" and "exit" buttons. The "bookmarks" button is missing its top.

**Comment by martykan** [comment]
Yeah, I have been looking into alternatives for a while. There is so many buttons that it's tight even in 720p.

**Comment by martykan** [comment]
Is it resolved now by switching to the new menu?

**Comment by txt-file** [comment]
yeah … it's much more usable now :-)
