### ISSUE TITLE
TOR

### ISSUE THREAD

**Issue by moshpirit** [martykan/webTube#2]
Thanks for the app! Looks pretty cool but I'd like to use it via TOR (probably using Orbot).

**Comment by martykan** [comment]
You can use transparent proxying in Orbot itself. I don't really want to encourage using Tor, because using it irresponsibly (ex. logging in to your YouTube account) deanonymizes your traffic.

**Comment by moshpirit** [comment]
But I think that this option is only available for root users. I don't use anything from Google (I would use the official app if I had an account) so not really interested in that. 
Maybe the solution could be precisely using TOR but disabling it if you use your account.

**Comment by martykan** [comment]
Alright, I'll add it in.

**Comment by moshpirit** [comment]
Thank you! :+1:

**Comment by martykan** [comment]
OK, done. I used the official Orbot library, so it should work reliably.

**Comment by moshpirit** [comment]
Cool! Thank you! :)

**Comment by moshpirit** [comment]
Thanks! there's no TOR option in the settings, how can I be sure that it's working? On my desktop, I use the TOR browser so the suggested videos are in other language but since WebTube allows us to select it manually and it's in Spain by default, I can't know it :(

**Comment by martykan** [comment]
You have to have Orbot installed.

**Comment by moshpirit** [comment]
And that's it? No need to change anything?

**Comment by martykan** [comment]
Just click on "Enable Tor" in the menu

**Comment by moshpirit** [comment]
I see a "Restricted mode" but no "Enable Tor"

**Comment by moshpirit** [comment]
Sorry, I've just found it on the (+) menu :)
