### ISSUE TITLE
Forwarded ports does not do the trick with tor enabled

### ISSUE THREAD

**Issue by gerroon** [martykan/webTube#28]
Hi

I forwarded both 9050 (socks) and 8118 (http) to test WT to see if it would work with ssh forwards. For some reason it does not. Is it that it might be looking for orbot binary or using different ports?

**Comment by gerroon** [comment]
Hold on this one. I might have some forwarding issues. I will close it when I get to the bottom of it.

**Comment by martykan** [comment]
Any updates?

**Comment by gerroon** [comment]
Hi

There was an issue with the forwards. As long as 8118 and 9050 is forwarded it works

**Comment by martykan** [comment]
Ok, thanks.
