### ISSUE TITLE
Description Copyed from NewPipe

### ISSUE THREAD

**Issue by theScrabi** [martykan/webTube#3]
Hei pall,

your app is kind of nice, although you took some "stuff" from NP, which is OK. But you should not copy the description, so NewPipe is still written in it!!!

Also if you are interested in working with us together, please join our slack group. We are open for everyone who creates free youtube related software:
https://github.com/theScrabi/NewPipe/issues/125

**Comment by martykan** [comment]
The description is written by the F-Droid repo maintainer (@krt16s) and has been already fixed, as seen in [this](https://gitlab.com/fdroid/fdroiddata/commit/5411d59ac14a57827de1eb236cbc2bc871698b7b) commit.

I am I big NewPipe fan and I'll be happy to help.

**Comment by krt16s** [comment]
Indeed, I was being sloppy there. Sorry for the noise :)

**Comment by timofonic** [comment]
If you copied code from NewPipe, it's a derivative work. Therefore you _must_ mention the original authors. I'll contact with Free Software Foundation about this, I hope this doesn't offend you! ;)

If you are a big fan of NewPipe...

Why don't you mention NewPipe in your project? Or even better...

Why don't you collaborate on NewPipe project? ;)

**Comment by theScrabi** [comment]
@timofonic: https://github.com/martykan/webTube/issues/1
Still this is not a copy!!!

@martykan: http://invite.chschtsch.ml/ You don't need to contribute to our code base, but it would be nice to stick in contact, and know what's going on. If you like :)

**Comment by timofonic** [comment]
@theScrabi 

I see. Sorry, I was overjudging! I've seen weird things in the past about that, specially from students that want to pass practices and such.

@martykan I hope you don't get annoyed. I'm tired of copycats and these days I overreact over them :P
