### ISSUE TITLE
FR: Media button controls

### ISSUE THREAD

**Issue by gerroon** [martykan/webTube#34]
Hi,

It will be awesome if WT can grab media button events from BT devices or headsets.

cheers

**Comment by martykan** [comment]
I don't have any headphones with buttons, so I can't test it properly, but I added some code in.

**Comment by gerroon** [comment]
Thanks.  I will test it out

**Comment by martykan** [comment]
I finally bought a headset and got it to work. I can't ensure that it will be compatible with everything, but it works pretty well so far.

**Comment by gerroon** [comment]
Thanks I will test it out.
