### ISSUE TITLE
Any advantages/disadvantages for devices with GAPPS?

### ISSUE THREAD

**Issue by Gitoffthelawn** [martykan/webTube#4]
This was obviously created for devices *without* GAPPS.  Great job!

Out of curiosity, for devices *with* GAPPS, are there any advantages or differences to using this app over the regular YouTube app?

**Comment by martykan** [comment]
Not really - it's basically the YouTube website, so it's not better than the native app, but it has most of it's features.

**Comment by Gitoffthelawn** [comment]
Thanks.  Does it differ from the YouTube mobile website?

**Comment by martykan** [comment]
It adds a couple things, like the floating action button.

**Comment by Gitoffthelawn** [comment]
Thanks for your help.
