### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.0.1.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [martykan/webTube#45]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.0.1.

**Comment by ildar** [comment]
the place for F-Droid issues is different:
https://gitlab.com/fdroid/fdroidclient/issues/

**Comment by locutis-of-borg-1999** [comment]
https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by theScrabi** [comment]
Happened to be that I was still around on gitlab, so I did a merge request about that issue.
https://gitlab.com/fdroid/fdroiddata/merge_requests/1232

**Comment by locutis-of-borg-1999** [comment]
:-)
