### ISSUE TITLE
Option to block and or reset cookies on close

### ISSUE THREAD

**Issue by dillbyrne** [martykan/webTube#50]
Hi martykan Thanks for your app. It works great.

If you have time could you and an option or options  to block and or reset cookies so that the recommended videos get reset and more importantly from a privacy perspective it would reduce the tracking surface of the user.

**Comment by martykan** [comment]
Fixed in #52

**Comment by dillbyrne** [comment]
@martykan @42SK  Great stuff :+1: Thanks.
