### ISSUE TITLE
No option to come back to "Mobile" 

### ISSUE THREAD

**Issue by moshpirit** [martykan/webTube#8]
Step to follow:

1. Open the app
2. Open the menu
3. Select "Desktop"

No way to return to the other view except deleting all data.

**Comment by martykan** [comment]
If you scroll all the way down to bottom, there is a link that says "Mobile version". There is also a blue banner on top saying "We've redirected you to the desktop website. Return to mobile YouTube."

**Comment by moshpirit** [comment]
Thanks, I pressed return several times but didn't work for me
