### ISSUE TITLE
local bookmarks [Feature request]

### ISSUE THREAD

**Issue by moshpirit** [martykan/webTube#9]
Would it be possible to be able to save YouTube videos locally without needing a Google account?

Thanks beforehand!

**Comment by martykan** [comment]
That would be nice, I'll work on it

**Comment by moshpirit** [comment]
Great, thanks!

**Comment by martykan** [comment]
Done! 

<img src="http://i.imgur.com/GfpeTAm.png" width="300">

**Comment by moshpirit** [comment]
Hahaha nice! :D
